// LEVEL
export const SET_LEVEL = 'SET_LEVEL';
export const INCREMENT_LEVEL = 'INCREMENT_LEVEL';
export const SET_HIGHEST_LEVEL = 'SET_HIGHEST_LEVEL';
export const SET_LEVEL_RATINGS = 'SET_LEVEL_RATINGS';

// SCORE
export const SET_SCORE = 'SET_SCORE';

// TRICOLOR
export const SET_TRICOLOR_MODE = 'SET_TRICOLOR_MODE';

// BOARD STATE CACHE
export const SET_BOARD_STATE_CACHE = 'SET_BOARD_STATE_CACHE';

// LEADERBOARD
export const SET_LEADERBOARD = 'SET_LEADERBOARD';

// ROUTES
export const SET_ROUTE = 'SET_ROUTE';

export const SET_MODAL = 'SET_MODAL';

// MODE
export const SET_MODE = 'SET_MODE';