// Recipes
export const SET_SEARCHED_RECIPES = 'SET_SEARCHED_RECIPES';

// Navigation
export const SET_TAB = 'SET_TAB';

export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD';
export const NAVIGATION_BACK = 'NAVIGATION_BACK';



// PROPAGATE SPECIFIC TYPES
export const SET_LEADERBOARD = 'SET_LEADERBOARD';