import { Dimensions } from 'react-native';
import Colors from '../../constants/colors';

const Width = Dimensions.get('window').width;

export default {
  levelPicker: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
  },
  levelPickerHeader: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
    width: Width * 0.9,
    marginTop: 30,
  },
  menuContainer: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backToMenu: {
    backgroundColor: Colors.darkRed,
    padding: 5,
    paddingLeft: 8,
    paddingRight: 8,
    borderRadius: 5,
    marginBottom: 20,
    flex: 1,
    justifyContent: 'center',
  },
  menuText: {
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 15,
    color: Colors.white,
    fontFamily: 'MontserratBold',
  },
  levelPickerText: {
    fontSize: 20,
    padding: 5,
    paddingLeft: 8,
    paddingRight: 8,
    fontFamily: 'MontserratBold',
  },
  levelPickerElement: {
    flex: 3,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  levelPickerBox: {
    backgroundColor: Colors.lightBrown,
    padding: 5,
    paddingLeft: 8,
    paddingRight: 8,
    borderRadius: 5,
    marginBottom: 20,
    width: '95%',
    flex: 1,
    justifyContent: 'center',
  },
  rows: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  columns: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cell: {
    flex: 1,
    flexDirection: 'row',
    borderRadius: 5,
    margin: 5,
    height: Width * 0.8 / 4 - 10 + 20,
    backgroundColor: Colors.green,
    borderWidth: 5,
    borderColor: Colors.lighterGray,
  },
  cellDisabled: {
    flex: 1,
    flexDirection: 'row',
    borderRadius: 5,
    margin: 5,
    height: Width * 0.8 / 4 - 10 + 20,
    backgroundColor: Colors.gray,
    opacity: 0.5,
    borderWidth: 5,
    borderColor: Colors.lighterGray,
  },
  innerCell: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cellText: {
    fontSize: Width * 0.1,
    color: Colors.white,
    fontFamily: 'MontserratBold',
  },
  ratingBox: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  star: {
    color: Colors.white,
    fontSize: 13,
  },
};
